### ISSUE TITLE
setData causing error with links

### ISSUE THREAD

**Issue by larsinsd** [sdrdis/jquery.flowchart#10]
When I try to run setData(), I am getting this error if there are existing links with the same name in the existing flowchart.

this.data.operators[t] is undefined

**Comment by sdrdis** [comment]
Thank you for your issue. I am a bit under water currently, I will try to take a look at it next week. Thank you for your patience.

**Comment by sdrdis** [comment]
The bug was apparently fixed by @dingguijin pull request. Thank you for submitting the issue.
