### ISSUE TITLE
Top/Bottom connector are necesary

### ISSUE THREAD

**Issue by carles9000** [sdrdis/jquery.flowchart#101]
Hi

At first fantastic lib congratulations to author. When you have a lot of operators the screen is horrible. If you can add operators at top or bottom maybe will be the perfect tool for dessign !

Regards.
Carles

**Comment by sdrdis** [comment]
Hi,

Vertical flowchart are now supported:

http://sebastien.drouyer.com/jquery.flowchart-demo/

Regards,

sdrdos
