### ISSUE TITLE
Set Operators Default Link Color

### ISSUE THREAD

**Issue by MadTomT** [sdrdis/jquery.flowchart#102]
Hi.

I've create an operator with several outputs on it. When a link is created from this I want the link color to be RED. How do I set the default color for all links from this specific operator ?

I've tried everything I can think of...  and not got anywhere.

Thanks

**Comment by MadTomT** [comment]
I've got this working... not sure it's the best way.. but it does what I need.
```
onLinkCreate: function (linkId, linkData) {
	if (linkData['fromOperator'] == uniqueID) {
		linkData['color'] = "#ff0040"
	}
	return true;
},
```

**Comment by sdrdis** [comment]
Sorry for my late answer. But this is it indeed!
