### ISSUE TITLE
Using Icons as Output Labels ?

### ISSUE THREAD

**Issue by MadTomT** [sdrdis/jquery.flowchart#104]
Hi 

Is it possible to use an icon as a output connector label ?
When I've tried this the script has simply used my html as the label, not the icon.

Thanks

**Comment by runette** [comment]
Good question - It seemed a good idea so I had a quick look.

As far as I can see approx line 543 sets the connector label using a .text method whereas I think the operator title uses a .heml method. this would be why you are seeing what you see.

You could try changing this to a .html method and seeing what effect that has. if you get it working yuo could submit it as a pull request. Or just update this issue so people know.

**Comment by MadTomT** [comment]
HI.
I changes the .text method to .html and changed my labels to:
`label: '<img src="img/flow.png" />',`

This seems to have worked, but I now have an issue with the links once I reload a save flow.
This doesn't affect all links, only some and I can't see why. I've I reload then it appears to work.

I'll raise this as a new issue
