### ISSUE TITLE
Occasionally links appear out of line.

### ISSUE THREAD

**Issue by MadTomT** [sdrdis/jquery.flowchart#105]
Hi
I've got a slight issue with links not always lining up, often they appear 2 /3 mm above the connector.
When this happens it doesn't affect all links, just some on the page.

I'm loading the saved flow using `$flowchart.flowchart('setData', data);` where data is  my saved flow.

Sometimes some of the links are out of line, If I move a operator relating to that link it lines up. I have to do that for all affected links/operators.

If I reload the data then it's fine ! Any reason why this would happen and how do I stop it ?

Thanks

**Comment by MadTomT** [comment]
I've changed the output connectors to images, this seems to have affected the layout slightly.

The output 1 class 'flowchart-operator-connector-set' is now deeper and that appears to be affecting input1's connector.  Any way to either set the connector align to the bottom, not top that may resolve this.

**Comment by MadTomT** [comment]
I've managed to sort this by setting a fixed line height and tweaking the CSS.

**Comment by runette** [comment]
It worked be good if posted the details I'd gotta you fixed our and what the limitations where - in case other people in the community want to see

**Comment by MadTomT** [comment]
Hi. Sorry I should have added this update.
`.flowchart-operator-connector` I added a max-height which matched my icons size.
This caused the connectors to be an even height and realign>

I then adjusted the arrow position to match the new connector.
`.flowchart-operator-outputs .flowchart-operator-connector-arrow 
.flowchart-operator-outputs .flowchart-operator-connector-small-arrow`
