### ISSUE TITLE
Change CSS of Operator by it's ID ?

### ISSUE THREAD

**Issue by MadTomT** [sdrdis/jquery.flowchart#109]
Hi.

I've got an operator who's ID 'site_1a', all ID's are unique.
Is there anyway I can change `.flowchart-operator-title` based on the operator ID ?

Thanks

**Comment by MadTomT** [comment]
When creating my operator, how do I add the ID to the DIV with class `flowchart-operator-title`
If I can do that then I can reference that specific DIV.

Thanks

**Comment by MadTomT** [comment]
I've sorted how to add an ID to each operator title div as it's created.

In the .js I've changed the following:

`_getOperatorFullElement: function (operatorData)  `
To 
`_getOperatorFullElement: function (operatorData, operatorId)`

and Updated the two mentions of this from
`            var fullElement = this._getOperatorFullElement(operatorData);`
To
`            var fullElement = this._getOperatorFullElement(operatorData,operatorId);`

Finally updated the line that creates the title DIV:
`            var $operator_title = $('<div id="' + operatorId + '" class="flowchart-operator-title"></div>');`

Now each title div has the ID of the operator.
Any issues with this ?

**Comment by ronaldoscotti** [comment]
Hi @MadTomT, how do you define the operatorId when you are creating the operators?

**Comment by MadTomT** [comment]
Each type of operator has it's id prefixed to identify it. eg: 'school_', 'staff_' etc

I then start with the Id as 000, then as each new operator is added I increment the value by 1. So I end up with: school_001, school_002, staff_003, school_004 etc..
