### ISSUE TITLE
Is it possible to convert `jquery. flowchartjs` into `markdown flow` syntax?

### ISSUE THREAD

**Issue by 625781186** [sdrdis/jquery.flowchart#117]
Is it possible to convert `jquery.flowchartjs` into `markdown flow` syntax, 
or to drive `jquer.flowchartjs` through `markdown flow` syntax?

![image](https://user-images.githubusercontent.com/30521429/71352790-2d249500-25b2-11ea-8764-022f7881af89.png)

**Comment by sdrdis** [comment]
Not directly, but you could easily convert the dictionary returned by getData.

**Comment by 625781186** [comment]
For this reason, I think this issue seems unnecessary .
https://github.com/adrai/flowchart.js/issues/193
However, it would be nice to drive `jquer.flowchartjs` through `markdown flow` syntax.
