### ISSUE TITLE
Manipulating operator body or creating custom operators

### ISSUE THREAD

**Issue by zekageri** [sdrdis/jquery.flowchart#122]
I want to create custom operator when dragged to the canvas. My goal is to put some more things in an operator such as datetime input and a text input next to the input output divs inside an operator.

Is it possible?

**Comment by Rob-ModernAnalytics** [comment]
Hi - this is definitely doable mostly with css but can be augmented with js code.  Here is a screen pic of an application I've created to build an ETL data pipeline.  The screen comprises two separate flowcharts - one of the "toolbar" and the other for the drawing canvas.  As you can see I've placed various icons for different "categories" of operators.

![image](https://user-images.githubusercontent.com/26229249/80841427-3bb03800-8bb4-11ea-97c0-ef781748de3d.png)

Rob
