### ISSUE TITLE
how to get operator area?

### ISSUE THREAD

**Issue by AlexKapustin** [sdrdis/jquery.flowchart#123]
Currently API allows to get position of operator, but it's not allowed to know size of operator.
Sometimes it's useful to build some extra layers (for example additional menu for active/selected operator).
For example, if I want to build additional menu on top of selected operator, it's not possible for me to adjust menu width, because I do not know operator width.

**Comment by AlexKapustin** [comment]
https://github.com/sdrdis/jquery.flowchart/pull/124 I created MR, to resolve the problem.
(Get client rect information)

**Comment by sdrdis** [comment]
Thanks for your contribution!
