### ISSUE TITLE
Error while adding class to operator on select

### ISSUE THREAD

**Issue by orkhanmeh** [sdrdis/jquery.flowchart#126]
$flowchart.flowchart('addClassOperator', operatorID, 'active')

calling the above function generates the error:
Uncaught Error: no such method 'addClassOperator' for flowchart widget instance

p.s Other methods work just fine.

**Comment by orkhanmeh** [comment]
I have solved it manually with jquery.

**Comment by MattRiddell** [comment]
Close out the ticket if you don't need any more help
