### ISSUE TITLE
$.flowchart is not a function

### ISSUE THREAD

**Issue by v3l1d** [sdrdis/jquery.flowchart#132]
I'm trying to draw a graph with my datas converted in operators and input/output, but i get this error 

![screenprof](https://user-images.githubusercontent.com/57458926/114845837-65ba3480-9ddc-11eb-9109-039edc35c566.PNG)

and this is the point of my script in which i get the error 
$('#example_2').flowchart({
          data: data,
          defaultLinkColor: '#000000',
          linkWidth: 2,
          //defaultOperatorClass: 'flowchart-custom-operator',
          onOperatorSelect: function(operatorId) {
              openNav($flowchart, operatorId, $flowchart.flowchart('getOperatorData', operatorId));
              return true;
          }
      });

**Comment by sdrdis** [comment]
Hi !

Did you import jquery ?

**Comment by v3l1d** [comment]
Yes, i did via CDN.
