### ISSUE TITLE
Swapping input and output locations and Background images/colors

### ISSUE THREAD

**Issue by wjrivera** [sdrdis/jquery.flowchart#14]
I was wondering if there was a way to swap the input and output locations, not just changing the name, but allowing the left side to act as the output and right side as the input.
Also
Is there a way to change the background of the nodes? By replacing it as colors or images?
Thank you

**Comment by sdrdis** [comment]
You should be able to change background and color of the nodes using css. Swapping inputs to left and right is not possible under the current implementation, but it should not be very difficult to implement (most could be done using css, but the plugin needs an option to invert the links directions...

**Comment by wjrivera** [comment]
The reason for my question was to make the UI look like a cycle, similar to my image below:
![capture](https://cloud.githubusercontent.com/assets/9951818/19895691/208b3afa-a028-11e6-8a78-f3c896f0fe16.JPG)
Do the lines have any sort of option to make them wrap around the object/nodes?
Thank you again for your time!

**Comment by sdrdis** [comment]
Not for the moment sorry ! I note it as a future feature.

**Comment by wjrivera** [comment]
Thank you so much!!
