### ISSUE TITLE
Limit draggable area (to div itself and/or to custom element)

### ISSUE THREAD

**Issue by MFatihMAR** [sdrdis/jquery.flowchart#18]
I'm able to move operators out of flowchart div. I know operators are `draggable` and they're [`containable`](http://api.jqueryui.com/draggable/#option-containment). Are you planning any support on this?
![image](https://cloud.githubusercontent.com/assets/12574651/20507332/b79df97e-b062-11e6-8290-2f5b9f11c92b.png)

**Comment by sdrdis** [comment]
Thanks again for the PR!
