### ISSUE TITLE
Question: Drag outside of scrollable div

### ISSUE THREAD

**Issue by Mike-Branham** [sdrdis/jquery.flowchart#22]
First great stuff, using it to show database dependencies.  The client is like WOW.

I'm using jquery.jspanel (jspanel.de) to hold div's of the table and fields.  When I click and drag, it works fine to drop it onto the chart_container, however it scrolls inside the panel, and not visible until dropped on the chart_container.  All works well after that as far as dragging, etc.  I'd prefer it to be visible while moving outside of that panel.  I've tried changing the z-index, but that didn't work.

I'm using your draggable and getOperatorData from the demo to create the operator.

Any suggestions?

Thanks in advance
-Mike

**Comment by Mike-Branham** [comment]
BTW, I figured it out.  Adding helper, appendTo, and zIndex to draggable seems to have worked.  Here's the code.

-Mike

            $draggableOperators.draggable({
                cursor: "move",
                opacity: 0.7,

                helper: 'clone', 
                appendTo: 'body',
                zIndex: 1000,

                helper: function(e) {
                  var $this = $(this);
                  var data = getOperatorData($this);
                  return $flowchart.flowchart('getOperatorElement', data);
                },
                stop: function(e, ui) {
                    var $this = $(this);
                    var elOffset = ui.offset;
                    var containerOffset = $container.offset();
                    if (elOffset.left > containerOffset.left &&
                        elOffset.top > containerOffset.top && 
                        elOffset.left < containerOffset.left + $container.width() &&
                        elOffset.top < containerOffset.top + $container.height()) {

                        var flowchartOffset = $flowchart.offset();

                        var relativeLeft = elOffset.left - flowchartOffset.left;
                        var relativeTop = elOffset.top - flowchartOffset.top;

                        var positionRatio = $flowchart.flowchart('getPositionRatio');
                        relativeLeft /= positionRatio;
                        relativeTop /= positionRatio;

                        var data = getOperatorData($this);
                        data.left = relativeLeft;
                        data.top = relativeTop;

                        $flowchart.flowchart('createOperator', 'op_' + operatorId, data);
                        operatorId++;
                    }
                }
            });

**Comment by sdrdis** [comment]
Hi Mike,

First, sorry for my late answer, I have been busy these last few months. I integrated your fix to the demo since it works there too. Consequently, I added you as a contributor in the README :smile:.

Thanks,

Sébastien
