### ISSUE TITLE
Error on dragging with latest Chrome version (Advanced Panzoom example)

### ISSUE THREAD

**Issue by lucasrego** [sdrdis/jquery.flowchart#26]
Hi,

The advanced example with Panzoom is not working on the latest version of Chrome. **Objects are not being dragged individually.**

All other examples work normally on http://sebastien.drouyer.com/jquery.flowchart-demo. The problem occurs only in "Advanced: panzoom view and operator creation using drag and drop".

It works normally in FireFox and earlier versions of Chrome, but does not work on the latest Chrome update (Version Version 55.0.2883.87).

Thanks if you can check.

**Comment by sdrdis** [comment]
Hi,

I checked and I could reproduce the problem. After merging #25, the problem disappeared (the demo now works in the latest version of chrome). So I guess you just have to pull the latest version of jquery.flowchart, refresh your browser and everything should be ok.

Thanks,
