### ISSUE TITLE
Link is missing when i reload data from any storage.

### ISSUE THREAD

**Issue by manickam91** [sdrdis/jquery.flowchart#56]
I loaded data into db after creating the chart. while reloading data using setData() i got all operators but not links.

**Comment by sdrdis** [comment]
Did you succeed to solve your problem ?

**Comment by manickam91** [comment]
Yes, i used  inbuilt method getData() to get complete data after drawing the chart and stored it. injected the retrieved data into setData() to reproduce the chart.
