### ISSUE TITLE
Output to multiple operator inputs

### ISSUE THREAD

**Issue by samcov** [sdrdis/jquery.flowchart#59]
A valid use case is where the output of one operator may feed the input of more than one operators input.

Currently if I have the output connected to the input of another operator(1), I can't connect that same output to the input of operator(2).

You may add additional outputs to accomplish this, but it presents the dilemma of having to know how many other operators you're going to connect to before hand.

The simple solution is to just draw links to as many inputs as the user requires.

**Question**: Is this possible?

**Comment by sdrdis** [comment]
Hi,

Yes, it is possible.

There are two solutions for this:
1. (recommended) Create a "multiple" connector as shown in:
http://sebastien.drouyer.com/jquery.flowchart-demo/#multiple

2. Try using the "multipleLinksOnInput" and "multipleLinksOnOutput" parameters.

Thanks, don't hesitate to ask any question,

**Comment by samcov** [comment]
**Thanks**, I knew I had to be missing something!
