### ISSUE TITLE
Programmatically change operator position

### ISSUE THREAD

**Issue by simmyg89** [sdrdis/jquery.flowchart#6]
Is there a way to change the operator position programmatically?

**Comment by sdrdis** [comment]
Sorry I am bit busy currently, I will take a look at your PR this weekend... You can probably find what you want with the method setOperatorData.

**Comment by hyyper** [comment]
I encountered the same question and @sdrdis hinted at the setOperatorData, which worked perfect. Just pass it the operatorId & operatorData. Keep mindful that the onOperatorDelete method must return true for this work properly. I was getting duplicates and couldn't understand why. 

setOperatorData doesn't manipulate the same operator but deletes and redraws it. Hopefully that helps.

**Comment by sdrdis** [comment]
The answer is spot on, thanks @hyyper. Sorry I didn't answer before.
