### ISSUE TITLE
is possible to put the operator beforehand with php?

### ISSUE THREAD

**Issue by samuelrojasp** [sdrdis/jquery.flowchart#8]

**Comment by sdrdis** [comment]
Just to be clear : you want to fill the flowchart using PHP ?

**Comment by samuelrojasp** [comment]
i have the divs before using javascript... i mean i want to use some existing divs.

**Comment by sdrdis** [comment]
Ok. So no it is not possible for the moment. You would probably be better of calling the plugin with JSON data...
