### ISSUE TITLE
Option to turn off event triggers when using setData

### ISSUE THREAD

**Issue by robincsamuel** [sdrdis/jquery.flowchart#85]
I have an event listener to make an API call `onLinkCreate`.  But later, if the page already has some operators and links, it's set using `setData`. `setData` is triggering `linkCreate` event, and thereby making unwanted API calls. 

Is there any way I can setData silently? If not, I think it's good to have that option.

**Comment by sdrdis** [comment]
There is no official way, however you could be a variable somewhere that indicates that setData as been called:

`
  isSettingData = true;
  $flowchart.setData(data);
  isSettingData = false;
`

 and simply make a return when linkCreate is called and this variable is set to `true`.
