### ISSUE TITLE
how to add multiple links from same connector arrow

### ISSUE THREAD

**Issue by umarsuhail** [sdrdis/jquery.flowchart#89]
i want to connect with multiple input from one output. i want to connect the link where ever i needed.

**Comment by runette** [comment]
I have a feeling the answer probably should be : This is open source
software. It does what it does. If you change it to make that happen -
please share since I am sure the rest of he community would be interested.
Thanks

**Comment by umarsuhail** [comment]
done by changing the value of multipleLinksOnOutput to true,
