### ISSUE TITLE
help me to get the mid point of the link

### ISSUE THREAD

**Issue by umarsuhail** [sdrdis/jquery.flowchart#91]
I want the mid point of the link between two operators. please help me on this issue

**Comment by runette** [comment]
I feel you are going to have to do some deep changes to do that - but I got interested in what the answer might be. The links are paths - so you could possibly (not checked in any way) find the path and use this 

https://stackoverflow.com/questions/25278029/have-a-path-point-to-the-middle-of-another-path.

What do you need it for ?

**Comment by runette** [comment]
and - again untested - looks like you can find the path since it is a child of an element configured as  :
            group.setAttribute('class', 'flowchart-link');
            group.setAttribute('data-link_id', linkId); 

i.e class="flowchart-link" and data-link_id is the relevant link id.

**Comment by runette** [comment]
if you do sort it out - please feed it back so that other people can use it :)
