### ISSUE TITLE
flowchart is not a function - $j = jQuery.noConflict()

### ISSUE THREAD

**Issue by J-Setzer** [sdrdis/jquery.flowchart#97]
The framework I'm using uses jQuery's noConflict mode (see https://api.jquery.com/jquery.noconflict/) to avoid problems with other libraries:

`$j = jQuery.noConflict();`

So my code always looks like `$j('#selector')` instead of `$('#selector')`

The _jquery.flowchart_ lib uses `$`. After including the script, I am not able to call the _flowchart()_ function on my target element:

`<div id="statemachine" data-id="1"></div>`

the script gets loaded dynamically, and this does work.

```
$j.getScript("resources/Jquery.flowchart/jquery.flowchart.js", function (data, textStatus, jqxhr) {
        console.log("jquery.flowchart.js loaded!");
        
        var e = $j('#statemachine');

        e.flowchart({
            data: getData()
        });
        
    });
```

The script gets loaded, and element `e` is defined. This is the console output:

![image](https://user-images.githubusercontent.com/20423093/44945252-4d40ab80-ade5-11e8-9fd0-7056afa57d04.png)

Can someone please help me to get jquery.flowchart running in noConflict mode or give me a hint what I'm doing wrong! Thanks a lot!

Regards,
Jan

**Comment by sdrdis** [comment]
It should work now. Sorry for the delay!
