### ISSUE TITLE
Link color subject to element type ?

### ISSUE THREAD

**Issue by MadTomT** [sdrdis/jquery.flowchart#99]
Hi

Lets say I have 4 different element types I can add to my flow.
Links from each should be a different color is there anyway I can do that ?

Thanks

**Comment by runette** [comment]
Each link in the json can have a color property. Do the rest in the back end logic

**Comment by MadTomT** [comment]
Hi
How do I change the color of a link ?
If this is my data how can outputs 1,2 & 3 have different link colors ?

```
	  var operatorData = {
        top: 60 + (operatorI * 20),
        left: 500 + (operatorI * 20),
        properties: {
			title: 'Test',
			inputs: {
				input_1: {
				label: '',
				}
			},
			outputs: {
		  		output_1: {
                 label: '1',
				 id: '1_' + operatorI,
				},
				output_2: {
                 label: '2',
				 id: '2_' + operatorI,
				},
				output_3: {
                 label: '3',
				 id: '3_' + operatorI,
				},
			}
        }
      };
```

Thanks

**Comment by runette** [comment]
Those are not links. The link is the line that goes from input to output. The link has it's own metadata in the getData data. the data looks like this :

**Comment by MadTomT** [comment]
Hi. Thanks for the reply.
I tried adding color to the links section of the above and that didn't seem to do anything. I also tried to use the following after a link was created, but I got errors the color wasn't defined..

`$flowchart.flowchart('setLinkMainColor', linkId, '#006600');`
Any advice on how to do this? Thanks

**Comment by runette** [comment]
I don't know about the problem with setLinkMainColor - I have never used that. Try going through getData, change the data, setData and see if that works.

About the former - to be very precise there is no "link section of the above" since the above is an instance of one operator data. Operator data and link data are two separate branches from the root.
